Data Challenge : Can you predict the tide ?
Author : Oumeima EL GHARBI
Date : November 2022

# PART 1 : Preprocessing

### Importing libraries

In [1]:
%reset -f

from functions import *

import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action="once")

%matplotlib inline
%autosave 300

Autosaving every 300 seconds


In [2]:
# Starting time
t0 = time()

seed = 42

#### Loading dataset

In [3]:
# load raw dataset
input_path = "./dataset/source/"
output_path = "./dataset/output/"


X_train_filename = "X_train_surge_new.npz"
Y_train_filename = "Y_train_surge.csv"
X_test_filename = "X_test_surge_new.npz"

X_train_file = "{}{}".format(input_path, X_train_filename)
Y_train_file = "{}{}".format(input_path, Y_train_filename)
X_test_file = "{}{}".format(input_path, X_test_filename)

In [4]:
X_train = np.load(X_train_file)
Y_train = pd.read_csv(Y_train_file)
X_test = np.load(X_test_file)

In [5]:
X_train

In [6]:
surge_train = np.array(Y_train)[:,1:]

In [7]:
surge_train

array([[ 0.58693592,  1.06958024,  0.76792754, ..., -0.42270688,
        -0.45623606, -0.82505705],
       [ 0.76792754, -0.1001619 ,  0.07077463, ..., -0.82505705,
        -0.99270295, -0.99270295],
       [ 0.07077463, -0.24428486, -0.35489084, ..., -0.99270295,
        -0.32211934, -0.88373311],
       ...,
       [ 0.48303332,  0.53330877,  1.44832196, ...,  1.22022298,
         1.44654495,  2.67036005],
       [ 1.44832196,  1.82036029,  1.66283054, ...,  2.67036005,
         2.62006628,  2.67874235],
       [ 1.66283054,  1.52876268,  1.28408882, ...,  2.67874235,
         1.22022298,  0.72566756]])

In [8]:
np.array(X_train)

array(['id_sequence', 't_slp', 'slp', 't_surge1_input', 'surge1_input',
       't_surge2_input', 'surge2_input', 't_surge1_output',
       't_surge2_output'], dtype='<U15')

In [9]:
pd.DataFrame(X_train)#.shape

0
0      id_sequence
1            t_slp
2              slp
3   t_surge1_input
4     surge1_input
5   t_surge2_input
6     surge2_input
7  t_surge1_output
8  t_surge2_output

In [10]:
X_train['slp'].shape

(5599, 40, 41, 41)

#### Making X or slp_train for X_train and X_test

##### Preparing X_train to train

In [11]:
slp_train = generate_X_train_test(X_train)

slp_train

array([[100849.72, 100797.72, 100754.72, ..., 101970.81, 101981.81,
        101990.81],
       [100940.37, 100881.37, 100823.37, ..., 101515.72, 101562.72,
        101611.72],
       [101862.91, 101879.91, 101894.91, ..., 101005.37, 101038.37,
        101076.37],
       ...,
       [102048.13, 102080.13, 102106.13, ..., 100781.81, 100724.81,
        100664.81],
       [102111.95, 102134.95, 102149.95, ..., 101352.13, 101376.13,
        101392.13],
       [101972.53, 101984.53, 101993.53, ..., 100412.28, 100450.28,
        100483.28]], dtype=float32)

##### Preparing X_test for the submission

In [12]:
slp_test = generate_X_train_test(X_test)
X_test['id_sequence']

array([5600, 5601, 5602, 5603, 5604, 5605, 5606, 5607, 5608, 5609, 5610,
       5611, 5612, 5613, 5614, 5615, 5616, 5617, 5618, 5619, 5620, 5621,
       5622, 5623, 5624, 5625, 5626, 5627, 5628, 5629, 5630, 5631, 5632,
       5633, 5634, 5635, 5636, 5637, 5638, 5639, 5640, 5641, 5642, 5643,
       5644, 5645, 5646, 5647, 5648, 5649, 5650, 5651, 5652, 5653, 5654,
       5655, 5656, 5657, 5658, 5659, 5660, 5661, 5662, 5663, 5664, 5665,
       5666, 5667, 5668, 5669, 5670, 5671, 5672, 5673, 5674, 5675, 5676,
       5677, 5678, 5679, 5680, 5681, 5682, 5683, 5684, 5685, 5686, 5687,
       5688, 5689, 5690, 5691, 5692, 5693, 5694, 5695, 5696, 5697, 5698,
       5699, 5700, 5701, 5702, 5703, 5704, 5705, 5706, 5707, 5708, 5709,
       5710, 5711, 5712, 5713, 5714, 5715, 5716, 5717, 5718, 5719, 5720,
       5721, 5722, 5723, 5724, 5725, 5726, 5727, 5728, 5729, 5730, 5731,
       5732, 5733, 5734, 5735, 5736, 5737, 5738, 5739, 5740, 5741, 5742,
       5743, 5744, 5745, 5746, 5747, 5748, 5749, 57

#### Making y or surge_train / Y_train

In [13]:
surge_train = generate_Y_train(Y_train)
surge_train

array([[ 0.58693592,  1.06958024,  0.76792754, ..., -0.42270688,
        -0.45623606, -0.82505705],
       [ 0.76792754, -0.1001619 ,  0.07077463, ..., -0.82505705,
        -0.99270295, -0.99270295],
       [ 0.07077463, -0.24428486, -0.35489084, ..., -0.99270295,
        -0.32211934, -0.88373311],
       ...,
       [ 0.48303332,  0.53330877,  1.44832196, ...,  1.22022298,
         1.44654495,  2.67036005],
       [ 1.44832196,  1.82036029,  1.66283054, ...,  2.67036005,
         2.62006628,  2.67874235],
       [ 1.66283054,  1.52876268,  1.28408882, ...,  2.67874235,
         1.22022298,  0.72566756]])

In [14]:
surge_train_df = Y_train_to_dataframe(surge_train, X_train)
surge_train_df

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
1      0.586936   1.069580   0.767928  -0.100162   0.070775  -0.244285   
2      0.767928  -0.100162   0.070775  -0.244285  -0.354891  -0.928031   
3      0.070775  -0.244285  -0.354891  -0.928031  -0.773853  -0.375001   
4     -0.354891  -0.928031  -0.773853  -0.375001  -0.361594  -0.210768   
5     -0.773853  -0.375001  -0.361594  -0.210768   0.288635  -0.726929   
...         ...        ...        ...        ...        ...        ...   
5595   1.451674   1.220407   0.556771   1.709754   0.483033   0.533309   
5596   0.556771   1.709754   0.483033   0.533309   1.448322   1.820360   
5597   0.483033   0.533309   1.448322   1.820360   1.662831   1.528763   
5598   1.448322   1.820360   1.662831   1.528763   1.284089   0.070775   
5599   1.662831   1.528763   1.284089   0.070775   0.888589   1.545521   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
1     -0.354891  -0.928031  -0.773853  -0.375001  -0.053886   0.356847   
2     -0.773853  -0.375001  -0.361594  -0.210768   0.348464   0.264641   
3     -0.361594  -0.210768   0.288635  -0.726929   0.901696   0.449052   
4      0.288635  -0.726929  -0.576103   1.160076   0.113760  -0.422707   
5     -0.576103   1.160076   0.442813   0.305393  -0.456236  -0.825057   
...         ...        ...        ...        ...        ...        ...   
5595   1.448322   1.820360   1.662831   1.528763   0.759197   0.884931   
5596   1.662831   1.528763   1.284089   0.070775   0.298171  -0.397560   
5597   1.284089   0.070775   0.888589   1.545521  -0.540059  -0.498148   
5598   0.888589   1.545521   1.166779   0.653970  -0.498148  -0.405942   
5599   1.166779   0.653970   0.409296   0.137809   0.164054   0.331700   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
1      0.348464   0.264641   0.901696   0.449052   0.113760  -0.422707   
2      0.901696   0.449052   0.113760  -0.422707  -0.456236  -0.825057   
3      0.113760  -0.422707  -0.456236  -0.825057  -0.992703  -0.992703   
4     -0.456236  -0.825057  -0.992703  -0.992703  -0.322119  -0.883733   
5     -0.992703  -0.992703  -0.322119  -0.883733  -0.473001  -0.422707   
...         ...        ...        ...        ...        ...        ...   
5595   0.298171  -0.397560  -0.540059  -0.498148  -0.498148  -0.405942   
5596  -0.540059  -0.498148  -0.498148  -0.405942   0.164054   0.331700   
5597  -0.498148  -0.405942   0.164054   0.331700   1.052577   1.220223   
5598   0.164054   0.331700   1.052577   1.220223   1.446545   2.670360   
5599   1.052577   1.220223   1.446545   2.670360   2.620066   2.678742   

      surge2_t8  surge2_t9  
1     -0.456236  -0.825057  
2     -0.992703  -0.992703  
3     -0.322119  -0.883733  
4     -0.473001  -0.422707  
5     -0.473001  -0.531677  
...         ...        ...  
5595   0.164054   0.331700  
5596   1.052577   1.220223  
5597   1.446545   2.670360  
5598   2.620066   2.678742  
5599   1.220223   0.725668  

[5599 rows x 20 columns]

#### Splitting train / test set using X_train and Y_train

In [15]:
from sklearn.model_selection import train_test_split

X_train_surge, X_val_surge, y_train_surge, y_val_surge = train_test_split(slp_train, surge_train_df, test_size=0.3, random_state=seed)

In [16]:
slp_train.shape

(5599, 3362)

In [17]:
surge_train.shape

(5599, 20)

In [18]:
X_train_surge.shape

(3919, 3362)

In [19]:
y_val_surge.shape

(1680, 20)

In [20]:
X_train_surge

array([[102176.35, 102156.35, 102133.35, ..., 101640.01, 101663.01,
        101685.01],
       [101805.57, 101868.57, 101921.57, ..., 100350.2 , 100314.2 ,
        100281.2 ],
       [102114.1 , 102082.1 , 102049.1 , ..., 101215.24, 101180.24,
        101145.24],
       ...,
       [101786.12, 101687.12, 101576.12, ..., 100236.8 , 100318.8 ,
        100393.8 ],
       [102499.41, 102499.41, 102497.41, ..., 100472.49, 100492.49,
        100510.49],
       [101569.21, 101633.21, 101687.21, ...,  98750.56,  98741.56,
         98742.56]], dtype=float32)

In [21]:
y_val_surge

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
4441  -0.167196  -0.234230  -0.110217  -0.029776   0.047313  -0.046535   
2472   0.238359   2.105255   0.888589   1.062877   1.103097  -1.638591   
3317  -0.096810  -0.100162  -0.103514   0.265173  -0.244285  -0.321374   
81     1.331013   0.553419   1.220407   0.637211  -0.013018  -0.150437   
4806   1.776788   3.053785   3.516319   2.557734   0.922106   2.068386   
...         ...        ...        ...        ...        ...        ...   
1392  -1.440841  -1.135836  -0.760446  -0.747039  -0.271098  -0.499014   
4351  -0.116920  -0.328077  -0.371649  -0.455442  -0.455442  -0.499014   
221   -1.420730  -1.561502  -1.702273  -1.826286  -1.779362  -1.283311   
1746  -0.163844  -0.458793  -0.006314  -0.090107  -0.250988  -0.368298   
628    0.070775  -0.971603  -0.877756  -1.427434  -1.507874  -0.944789   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
4441  -0.354891  -0.405166  -0.314670  -0.690061  -0.104180  -0.162856   
2472  -1.145891  -0.321374  -0.579455  -0.666599  -1.336377  -0.967556   
3317  -0.552641  -0.579455  -0.646488  -0.110217   1.002283   0.960372   
81     0.141160   0.198139   0.060720  -0.371649  -0.925645  -1.403435   
4806   1.713106   1.153373   2.406907   1.947725   0.901696   1.236988   
...         ...        ...        ...        ...        ...        ...   
1392  -0.539234  -0.696764  -0.874404  -0.901217   1.295664   1.589044   
4351  -0.143734  -0.009666  -0.096810  -0.485607  -0.364031  -0.322119   
221   -1.249794  -0.921328  -0.991713  -0.777205  -0.380795   0.843020   
1746  -0.214120   0.208194   0.074126  -0.056590   0.423905   0.524492   
628   -0.418573  -0.254340   0.258470   0.808148   0.910078   0.264641   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
4441  -0.104180  -0.548441  -0.783146  -0.481383  -0.774763  -0.422707   
2472  -0.892115  -0.011974  -0.095797   0.105378  -0.095797  -0.162856   
3317   0.893313   0.943607   0.700521   0.457434   0.365229   0.608315   
81    -1.252554  -1.420200  -1.026232  -0.833439  -0.045504  -0.028739   
4806   0.717285   0.650227   0.708903   0.356847   0.474199   0.222730   
...         ...        ...        ...        ...        ...        ...   
1392   1.228605   0.273024  -0.305355  -0.355649  -0.716087  -1.051379   
4351  -0.489765  -0.791528  -0.556824  -0.690940  -0.422707  -0.674176   
221   -0.028739  -0.120944  -0.540059  -0.313737  -1.219025  -1.235790   
1746   0.750814   0.532875   1.060959   0.641845   0.708903   0.775961   
628   -0.095797  -0.313737  -0.062268  -0.146091  -0.347266  -1.068144   

      surge2_t8  surge2_t9  
4441  -0.296972   0.398758  
2472   0.113760   0.331700  
3317   0.289788   0.390376  
81    -0.347266  -0.975938  
4806   0.247877   0.055084  
...         ...        ...  
1392  -0.489765  -0.188003  
4351  -0.196385  -0.313737  
221   -1.587846  -1.638140  
1746   0.616698   0.474199  
628   -1.277701  -0.917262  

[1680 rows x 20 columns]

In [22]:
pd.DataFrame(X_train["id_sequence"])

0
0        1
1        2
2        3
3        4
4        5
...    ...
5594  5595
5595  5596
5596  5597
5597  5598
5598  5599

[5599 rows x 1 columns]

In [23]:
pd.DataFrame(Y_train)

id_sequence  surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  \
0               1   0.586936   1.069580   0.767928  -0.100162   0.070775   
1               2   0.767928  -0.100162   0.070775  -0.244285  -0.354891   
2               3   0.070775  -0.244285  -0.354891  -0.928031  -0.773853   
3               4  -0.354891  -0.928031  -0.773853  -0.375001  -0.361594   
4               5  -0.773853  -0.375001  -0.361594  -0.210768   0.288635   
...           ...        ...        ...        ...        ...        ...   
5594         5595   1.451674   1.220407   0.556771   1.709754   0.483033   
5595         5596   0.556771   1.709754   0.483033   0.533309   1.448322   
5596         5597   0.483033   0.533309   1.448322   1.820360   1.662831   
5597         5598   1.448322   1.820360   1.662831   1.528763   1.284089   
5598         5599   1.662831   1.528763   1.284089   0.070775   0.888589   

      surge1_t5  surge1_t6  surge1_t7  surge1_t8  ...  surge2_t0  surge2_t1  \
0     -0.244285  -0.354891  -0.928031  -0.773853  ...  -0.053886   0.356847   
1     -0.928031  -0.773853  -0.375001  -0.361594  ...   0.348464   0.264641   
2     -0.375001  -0.361594  -0.210768   0.288635  ...   0.901696   0.449052   
3     -0.210768   0.288635  -0.726929  -0.576103  ...   0.113760  -0.422707   
4     -0.726929  -0.576103   1.160076   0.442813  ...  -0.456236  -0.825057   
...         ...        ...        ...        ...  ...        ...        ...   
5594   0.533309   1.448322   1.820360   1.662831  ...   0.759197   0.884931   
5595   1.820360   1.662831   1.528763   1.284089  ...   0.298171  -0.397560   
5596   1.528763   1.284089   0.070775   0.888589  ...  -0.540059  -0.498148   
5597   0.070775   0.888589   1.545521   1.166779  ...  -0.498148  -0.405942   
5598   1.545521   1.166779   0.653970   0.409296  ...   0.164054   0.331700   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
0      0.348464   0.264641   0.901696   0.449052   0.113760  -0.422707   
1      0.901696   0.449052   0.113760  -0.422707  -0.456236  -0.825057   
2      0.113760  -0.422707  -0.456236  -0.825057  -0.992703  -0.992703   
3     -0.456236  -0.825057  -0.992703  -0.992703  -0.322119  -0.883733   
4     -0.992703  -0.992703  -0.322119  -0.883733  -0.473001  -0.422707   
...         ...        ...        ...        ...        ...        ...   
5594   0.298171  -0.397560  -0.540059  -0.498148  -0.498148  -0.405942   
5595  -0.540059  -0.498148  -0.498148  -0.405942   0.164054   0.331700   
5596  -0.498148  -0.405942   0.164054   0.331700   1.052577   1.220223   
5597   0.164054   0.331700   1.052577   1.220223   1.446545   2.670360   
5598   1.052577   1.220223   1.446545   2.670360   2.620066   2.678742   

      surge2_t8  surge2_t9  
0     -0.456236  -0.825057  
1     -0.992703  -0.992703  
2     -0.322119  -0.883733  
3     -0.473001  -0.422707  
4     -0.473001  -0.531677  
...         ...        ...  
5594   0.164054   0.331700  
5595   1.052577   1.220223  
5596   1.446545   2.670360  
5597   2.620066   2.678742  
5598   1.220223   0.725668  

[5599 rows x 21 columns]

In [24]:
X_train_surge.shape

(3919, 3362)

In [25]:
y_train_surge.shape

(3919, 20)

#### Saving testing set

In [26]:
y_val_surge.to_csv(output_path + "Y_val_true.csv", index_label='id_sequence', sep=',')

# Part II : Predictive modeling

In [27]:
X_train_surge

array([[102176.35, 102156.35, 102133.35, ..., 101640.01, 101663.01,
        101685.01],
       [101805.57, 101868.57, 101921.57, ..., 100350.2 , 100314.2 ,
        100281.2 ],
       [102114.1 , 102082.1 , 102049.1 , ..., 101215.24, 101180.24,
        101145.24],
       ...,
       [101786.12, 101687.12, 101576.12, ..., 100236.8 , 100318.8 ,
        100393.8 ],
       [102499.41, 102499.41, 102497.41, ..., 100472.49, 100492.49,
        100510.49],
       [101569.21, 101633.21, 101687.21, ...,  98750.56,  98741.56,
         98742.56]], dtype=float32)

In [28]:
y_train_surge

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
5569   0.013796   0.000389   0.315448   0.107643  -0.086755   0.010444   
2837   0.845017   0.556771   1.857229   0.372427  -0.914624  -0.304615   
84     0.141160   0.198139   0.060720  -0.371649   0.265173   1.297496   
3659  -0.854294  -0.904569  -1.008472  -1.078857  -1.072154  -0.669950   
791   -0.814073  -0.807370  -0.961548  -1.162650  -1.380510  -1.112374   
...         ...        ...        ...        ...        ...        ...   
3773   1.072932   1.049470   0.741114   0.707597   0.848368   0.499792   
5192  -0.187306   0.070775   0.241711   0.402593   0.945567   1.448322   
5227  -0.180603  -0.086755   0.754521   0.054016   0.975733   0.228304   
5391   0.395889   0.808148   0.590288   0.348965   0.077478   0.238359   
861    2.721967   2.671691   2.095199  -0.073348  -1.330235  -1.538040   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
5569   0.271876   0.375779   0.281932   0.271876   0.432287   0.516110   
2837  -0.411870  -0.750391  -0.626378  -0.559344  -1.302848  -1.042997   
84     1.860581   1.284089   1.274034  -0.133679  -0.045504  -0.028739   
3659  -0.562696  -0.006314   0.245063   0.332207  -5.762229  -4.194740   
791   -0.626378  -0.123624   0.214898   0.000389  -1.135202  -1.026232   
...         ...        ...        ...        ...        ...        ...   
3773   0.335559   1.485191   1.565631   1.213703   0.465816  -0.540059   
5192   0.868478   0.781334   0.204842  -0.039831   0.155671   0.063466   
5227   0.224953  -0.190658  -0.328077  -0.485607  -0.070650   0.281406   
5391   0.188084   0.543364   1.062877   0.295338   0.901696   0.901696   
861   -1.501171  -0.730281  -0.817425  -0.944789  -1.763874  -1.344759   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
5569   0.105378   0.130525   0.440670   0.415523   0.138907   0.298171   
2837  -1.084908  -0.783146  -0.992703  -1.571081  -1.403435  -1.017850   
84    -0.347266  -0.975938  -0.908880  -1.219025  -1.260936  -1.068144   
3659  -5.720317  -4.286945  -4.999440  -4.949146  -4.270180  -4.714442   
791   -0.959174  -0.607117  -0.841822  -0.355649  -0.514912  -0.196385   
...         ...        ...        ...        ...        ...        ...   
3773  -0.674176  -0.975938  -0.489765  -0.372413   0.340082   0.599933   
5192   0.390376   0.507728   0.306553   0.365229   0.432287   0.088613   
5227  -0.020357   0.197583   0.004790   0.490963   0.071849   0.843020   
5391   0.331700   0.692138  -0.196385  -0.296972  -0.850204  -0.598735   
861   -1.001085  -0.858586  -0.481383   0.700521   0.189201   0.407140   

      surge2_t8  surge2_t9  
5569   0.122142   0.340082  
2837  -0.313737  -0.598735  
84    -0.732852  -0.196385  
3659  -3.993565  -3.054748  
791   -0.003592  -0.548441  
...         ...        ...  
3773   0.348464   0.314935  
5192   0.080231  -0.179620  
5227   0.457434   0.558022  
5391  -0.892115  -0.598735  
861    0.264641   0.901696  

[3919 rows x 20 columns]

#### Baseline / Benchmark : Ball Tree

In [29]:
from sklearn.neighbors import BallTree

# 1) fit
tree = BallTree(X_train_surge, metric='l2')

# 2) predict
y_val_surge_pred_ballTree = []; k = 40
for i in range(X_val_surge.shape[0]):
    dist, ind = tree.query([X_val_surge[i]], k=k)
    y_val_surge_pred_ballTree.append(np.mean(surge_train[ind[0]], axis=0)) # we get indexes in surge_train (Y_train) where all the training data is

# 3) to matrix
y_val_surge_pred_ballTree = np.array(y_val_surge_pred_ballTree)

# 4) save
save_y_pred("BallTree", output_path, y_val_surge_pred_ballTree, y_val_surge.index, submit=False)

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
4441  -0.182027  -0.049300   0.063820   0.046978  -0.151862  -0.185798   
2472  -0.179848  -0.162001  -0.275037  -0.135606  -0.084912   0.068009   
3317  -0.269925  -0.080638  -0.120272  -0.198953  -0.255932  -0.203813   
81    -0.117172   0.118034  -0.059104  -0.141136  -0.056590   0.039771   
4806  -0.019973   0.236265   0.138395  -0.110049  -0.266909  -0.253502   
...         ...        ...        ...        ...        ...        ...   
1392   0.014466  -0.089353  -0.120859  -0.140550  -0.220488  -0.254675   
4351  -0.108541  -0.054579   0.060217   0.048151   0.053346  -0.129657   
221   -0.228867  -0.096307   0.072953  -0.098318  -0.122702  -0.098821   
1746  -0.297074  -0.404664  -0.392765  -0.368214  -0.387737  -0.376677   
628   -0.241101  -0.118093  -0.064466  -0.175826  -0.083320  -0.020056   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
4441  -0.054663   0.025024   0.072032   0.075467  -0.284399  -0.236620   
2472   0.005668   0.030973  -0.071337  -0.224091  -0.113819   0.018202   
3317  -0.028100  -0.052568  -0.188395  -0.228783  -0.487251  -0.492909   
81    -0.108374  -0.015951  -0.083487  -0.082649  -0.302421  -0.261138   
4806  -0.418154  -0.545183  -0.583477  -0.375336  -0.099569  -0.188003   
...         ...        ...        ...        ...        ...        ...   
1392  -0.158733  -0.225767  -0.220404  -0.057009  -0.376185  -0.316671   
4351  -0.074773  -0.066729  -0.117591  -0.160157  -0.174591  -0.269730   
221    0.007344  -0.083571  -0.299336  -0.129489  -0.252127  -0.227190   
1746  -0.475887  -0.471865  -0.317436  -0.121110  -0.027691  -0.028949   
628    0.098007   0.063904  -0.017207   0.067507  -0.044456  -0.087415   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
4441  -0.237877  -0.136661  -0.152797  -0.165580  -0.039636   0.009191   
2472   0.023650   0.016945  -0.092444  -0.120106  -0.157617  -0.110466   
3317  -0.441986  -0.464199  -0.499195  -0.530838  -0.472791  -0.479078   
81    -0.218808  -0.241440  -0.264072  -0.241021  -0.300744  -0.265958   
4806  -0.134775  -0.228657  -0.164742  -0.243326  -0.177944  -0.150701   
...         ...        ...        ...        ...        ...        ...   
1392  -0.231171  -0.211473  -0.197223  -0.194708  -0.221322  -0.221741   
4351  -0.299906  -0.422916  -0.504644  -0.533144  -0.567092  -0.539849   
221   -0.154264  -0.066459  -0.122411  -0.217341  -0.168095  -0.211263   
1746  -0.044456   0.026584  -0.063735  -0.058915  -0.112772  -0.157826   
628   -0.182764  -0.291105  -0.397141  -0.400284  -0.447644  -0.454769   

      surge2_t8  surge2_t9  
4441   0.047330   0.006886  
2472  -0.005897  -0.004011  
3317  -0.396093  -0.361307  
81    -0.399446  -0.368012  
4806  -0.200576  -0.224046  
...         ...        ...  
1392  -0.278322  -0.382472  
4351  -0.499614  -0.436328  
221   -0.283980  -0.289847  
1746  -0.252756  -0.288381  
628   -0.421869  -0.323586  

[1680 rows x 20 columns]

#### 1) Kernel Ridge

In [30]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.kernel_ridge import KernelRidge

In [31]:
y_train_surge.values

array([[ 1.37957876e-02,  3.89000943e-04,  3.15448487e-01, ...,
         2.98170509e-01,  1.22142310e-01,  3.40081985e-01],
       [ 8.45016559e-01,  5.56770646e-01,  1.85722895e+00, ...,
        -1.01784984e+00, -3.13737041e-01, -5.98735077e-01],
       [ 1.41160261e-01,  1.98139104e-01,  6.07195408e-02, ...,
        -1.06814361e+00, -7.32851800e-01, -1.96384908e-01],
       ...,
       [-1.80602619e-01, -8.67551122e-02,  7.54520749e-01, ...,
         8.43019697e-01,  4.57434118e-01,  5.58021660e-01],
       [ 3.95889207e-01,  8.08147896e-01,  5.90287613e-01, ...,
        -5.98735077e-01, -8.92115409e-01, -5.98735077e-01],
       [ 2.72196669e+00,  2.67169124e+00,  2.09519941e+00, ...,
         4.07140347e-01,  2.64641328e-01,  9.01695763e-01]])

In [32]:
estimator = KernelRidge(kernel='rbf') # default = Linear
# Valid values for metric are: [‘additive_chi2’, ‘chi2’, ‘linear’, ‘poly’, ‘polynomial’, ‘rbf’, ‘laplacian’, ‘sigmoid’, ‘cosine’]
regr_ridge = MultiOutputRegressor(estimator).fit(X_train_surge, y_train_surge)


In [33]:
regr_ridge.predict(X_train_surge[[0]])

array([[ 6.89638653e-03,  1.94457971e-04,  1.57689779e-01,
         5.38098864e-02, -4.33680776e-02,  5.22090439e-03,
         1.35908511e-01,  1.87848458e-01,  1.40934958e-01,
         1.35908511e-01,  2.16096386e-01,  2.57998704e-01,
         5.26773466e-02,  6.52480420e-02,  2.20286618e-01,
         2.07715923e-01,  6.94382738e-02,  1.49052678e-01,
         6.10578102e-02,  1.70003837e-01]])

In [34]:
y_val_surge_pred_ridge = regr_ridge.predict(X_val_surge)
y_val_surge_pred_ridge

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
save_y_pred("KernelRidge", output_path, y_val_surge_pred_ridge, y_val_surge.index, submit=False)

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
4441        0.0        0.0        0.0        0.0        0.0        0.0   
2472        0.0        0.0        0.0        0.0        0.0        0.0   
3317        0.0        0.0        0.0        0.0        0.0        0.0   
81          0.0        0.0        0.0        0.0        0.0        0.0   
4806        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1392        0.0        0.0        0.0        0.0        0.0        0.0   
4351        0.0        0.0        0.0        0.0        0.0        0.0   
221         0.0        0.0        0.0        0.0        0.0        0.0   
1746        0.0        0.0        0.0        0.0        0.0        0.0   
628         0.0        0.0        0.0        0.0        0.0        0.0   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
4441        0.0        0.0        0.0        0.0        0.0        0.0   
2472        0.0        0.0        0.0        0.0        0.0        0.0   
3317        0.0        0.0        0.0        0.0        0.0        0.0   
81          0.0        0.0        0.0        0.0        0.0        0.0   
4806        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1392        0.0        0.0        0.0        0.0        0.0        0.0   
4351        0.0        0.0        0.0        0.0        0.0        0.0   
221         0.0        0.0        0.0        0.0        0.0        0.0   
1746        0.0        0.0        0.0        0.0        0.0        0.0   
628         0.0        0.0        0.0        0.0        0.0        0.0   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
4441        0.0        0.0        0.0        0.0        0.0        0.0   
2472        0.0        0.0        0.0        0.0        0.0        0.0   
3317        0.0        0.0        0.0        0.0        0.0        0.0   
81          0.0        0.0        0.0        0.0        0.0        0.0   
4806        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1392        0.0        0.0        0.0        0.0        0.0        0.0   
4351        0.0        0.0        0.0        0.0        0.0        0.0   
221         0.0        0.0        0.0        0.0        0.0        0.0   
1746        0.0        0.0        0.0        0.0        0.0        0.0   
628         0.0        0.0        0.0        0.0        0.0        0.0   

      surge2_t8  surge2_t9  
4441        0.0        0.0  
2472        0.0        0.0  
3317        0.0        0.0  
81          0.0        0.0  
4806        0.0        0.0  
...         ...        ...  
1392        0.0        0.0  
4351        0.0        0.0  
221         0.0        0.0  
1746        0.0        0.0  
628         0.0        0.0  

[1680 rows x 20 columns]

In [36]:
y_val_surge

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
4441  -0.167196  -0.234230  -0.110217  -0.029776   0.047313  -0.046535   
2472   0.238359   2.105255   0.888589   1.062877   1.103097  -1.638591   
3317  -0.096810  -0.100162  -0.103514   0.265173  -0.244285  -0.321374   
81     1.331013   0.553419   1.220407   0.637211  -0.013018  -0.150437   
4806   1.776788   3.053785   3.516319   2.557734   0.922106   2.068386   
...         ...        ...        ...        ...        ...        ...   
1392  -1.440841  -1.135836  -0.760446  -0.747039  -0.271098  -0.499014   
4351  -0.116920  -0.328077  -0.371649  -0.455442  -0.455442  -0.499014   
221   -1.420730  -1.561502  -1.702273  -1.826286  -1.779362  -1.283311   
1746  -0.163844  -0.458793  -0.006314  -0.090107  -0.250988  -0.368298   
628    0.070775  -0.971603  -0.877756  -1.427434  -1.507874  -0.944789   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
4441  -0.354891  -0.405166  -0.314670  -0.690061  -0.104180  -0.162856   
2472  -1.145891  -0.321374  -0.579455  -0.666599  -1.336377  -0.967556   
3317  -0.552641  -0.579455  -0.646488  -0.110217   1.002283   0.960372   
81     0.141160   0.198139   0.060720  -0.371649  -0.925645  -1.403435   
4806   1.713106   1.153373   2.406907   1.947725   0.901696   1.236988   
...         ...        ...        ...        ...        ...        ...   
1392  -0.539234  -0.696764  -0.874404  -0.901217   1.295664   1.589044   
4351  -0.143734  -0.009666  -0.096810  -0.485607  -0.364031  -0.322119   
221   -1.249794  -0.921328  -0.991713  -0.777205  -0.380795   0.843020   
1746  -0.214120   0.208194   0.074126  -0.056590   0.423905   0.524492   
628   -0.418573  -0.254340   0.258470   0.808148   0.910078   0.264641   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
4441  -0.104180  -0.548441  -0.783146  -0.481383  -0.774763  -0.422707   
2472  -0.892115  -0.011974  -0.095797   0.105378  -0.095797  -0.162856   
3317   0.893313   0.943607   0.700521   0.457434   0.365229   0.608315   
81    -1.252554  -1.420200  -1.026232  -0.833439  -0.045504  -0.028739   
4806   0.717285   0.650227   0.708903   0.356847   0.474199   0.222730   
...         ...        ...        ...        ...        ...        ...   
1392   1.228605   0.273024  -0.305355  -0.355649  -0.716087  -1.051379   
4351  -0.489765  -0.791528  -0.556824  -0.690940  -0.422707  -0.674176   
221   -0.028739  -0.120944  -0.540059  -0.313737  -1.219025  -1.235790   
1746   0.750814   0.532875   1.060959   0.641845   0.708903   0.775961   
628   -0.095797  -0.313737  -0.062268  -0.146091  -0.347266  -1.068144   

      surge2_t8  surge2_t9  
4441  -0.296972   0.398758  
2472   0.113760   0.331700  
3317   0.289788   0.390376  
81    -0.347266  -0.975938  
4806   0.247877   0.055084  
...         ...        ...  
1392  -0.489765  -0.188003  
4351  -0.196385  -0.313737  
221   -1.587846  -1.638140  
1746   0.616698   0.474199  
628   -1.277701  -0.917262  

[1680 rows x 20 columns]

#### 2) XGBoost

In [37]:
from xgboost import XGBRegressor

estimator = XGBRegressor(random_state=seed)
regr_XGBoost = MultiOutputRegressor(estimator).fit(X_train_surge, y_train_surge)

In [38]:
y_val_surge_pred_XGBoost = regr_XGBoost.predict(X_val_surge)
y_val_surge_pred_XGBoost

array([[-0.17394245, -0.07076971, -0.35313022, ..., -0.3765128 ,
        -0.05057035,  0.23735075],
       [ 0.61477417,  1.1349449 ,  1.5644692 , ...,  0.34753063,
         0.3756748 , -0.30959523],
       [ 0.20340942, -0.13879962,  0.00546361, ...,  0.19692692,
        -0.04792346,  0.0370005 ],
       ...,
       [-0.92727125, -1.1750612 , -1.4002796 , ...,  0.11028803,
         0.8300514 ,  0.48890892],
       [ 0.05323436, -0.01420574,  0.07312743, ...,  0.01672565,
        -0.26626652,  0.35633314],
       [ 0.25047988,  0.31369486, -0.03632465, ...,  0.4509365 ,
         0.10584661, -0.20588161]], dtype=float32)

In [39]:
save_y_pred("XGBoost", output_path, y_val_surge_pred_XGBoost, y_val_surge.index, submit=False)

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
4441  -0.173942  -0.070770  -0.353130  -0.383810  -0.505295  -0.307391   
2472   0.614774   1.134945   1.564469   1.031873   1.309477   1.755210   
3317   0.203409  -0.138800   0.005464  -0.185794   0.082401  -0.386898   
81     1.172857   1.126813   0.657712   0.867534   0.631532   0.124433   
4806   1.079612   1.182355   1.225871   1.077304   1.118167   0.891174   
...         ...        ...        ...        ...        ...        ...   
1392  -1.256905  -0.620431  -0.806367  -0.610411  -1.205162  -0.552843   
4351  -0.323627  -0.587912  -0.659794  -1.061428  -1.153828  -0.729594   
221   -0.927271  -1.175061  -1.400280  -1.622731  -1.067377  -0.850352   
1746   0.053234  -0.014206   0.073127  -0.081643   0.197606   0.024559   
628    0.250480   0.313695  -0.036325  -0.804061  -0.465514   0.019093   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
4441  -0.731394  -0.200193  -0.752075  -0.816275  -0.316694   0.238220   
2472   0.717624   1.367895   1.298472   0.460322  -0.720934  -0.082967   
3317  -0.892648   0.187614  -0.042331  -0.180237   0.352511   0.461237   
81     0.292626  -0.229069  -0.219759   0.091416  -0.375403  -0.566127   
4806   1.609118   0.461662   0.388083   0.231583   1.090408   0.249673   
...         ...        ...        ...        ...        ...        ...   
1392  -0.535135  -0.245093  -1.260429  -0.326143   2.083113   1.710531   
4351  -0.518364  -0.462018  -0.274667  -0.293458  -0.347720  -0.445304   
221   -0.924509  -0.667455  -0.652718  -0.598471   0.566718   0.269512   
1746  -0.152650   0.687059   0.114019   0.138354   0.455451   0.261056   
628    0.195546  -0.094372  -0.532104   0.645202   1.537438   0.803774   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
4441  -0.123579  -0.314661  -0.252999  -0.475811   0.127526  -0.376513   
2472   0.211081   0.009084  -0.192652   0.167428  -0.577683   0.347531   
3317   0.031217  -0.058290  -0.208260   0.149302  -0.134528   0.196927   
81    -0.929993  -1.160924  -1.246985  -0.691676  -0.919890  -0.600992   
4806   1.502108   1.518855   1.408874   1.435064   0.964953   0.677888   
...         ...        ...        ...        ...        ...        ...   
1392   1.798219   0.965244   0.877634   0.823777   1.051440   0.894268   
4351   0.231904  -0.292358  -0.239131   0.061368  -0.086685   0.034887   
221    1.051771   0.476219   0.416763   0.587012   0.497564   0.110288   
1746   0.215103   0.150538   0.484324   0.186388   0.268131   0.016726   
628    0.141941   0.088704  -0.226542  -0.656551  -0.072673   0.450936   

      surge2_t8  surge2_t9  
4441  -0.050570   0.237351  
2472   0.375675  -0.309595  
3317  -0.047923   0.037000  
81    -0.460480  -0.662106  
4806   0.806588   0.308270  
...         ...        ...  
1392   1.374831   0.356735  
4351  -0.119078   0.270711  
221    0.830051   0.488909  
1746  -0.266267   0.356333  
628    0.105847  -0.205882  

[1680 rows x 20 columns]

#### 3) Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

estimator = RandomForestRegressor(random_state=seed)
regr_RFR = MultiOutputRegressor(estimator).fit(X_train_surge, y_train_surge)

y_val_surge_pred_RFR = regr_RFR.predict(X_val_surge)

save_y_pred("RFR", output_path, y_val_surge_pred_RFR, y_val_surge.index, submit=False)

#### 4) SVR

In [54]:
from sklearn.svm import SVR

estimator = SVR(kernel='rbf')
regr_SVR = MultiOutputRegressor(estimator).fit(X_train_surge, y_train_surge)

y_val_surge_pred_SVR = regr_SVR.predict(X_val_surge)

save_y_pred("SVR", output_path, y_val_surge_pred_SVR, y_val_surge.index, submit=False)

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
4441  -0.247597  -0.211064  -0.282102  -0.392997  -0.463498  -0.466259   
2472   0.572923   1.205507   0.762563   0.770125   0.801942   0.348437   
3317   0.191325  -0.223647  -0.423724  -0.412265  -0.384088  -0.295603   
81     1.183496   1.021942   0.907097   0.549792   0.208992   0.103292   
4806   1.129001   1.071098   0.856926   0.868327   0.916647   1.121682   
...         ...        ...        ...        ...        ...        ...   
1392  -0.847464  -0.729394  -0.478737  -0.571919  -0.816197  -0.890224   
4351  -0.431684  -0.570863  -0.752220  -0.808735  -0.808566  -0.694422   
221   -0.941483  -0.946069  -1.006190  -0.997230  -0.818067  -0.774965   
1746  -0.294947  -0.264980  -0.212398  -0.061770  -0.198787  -0.218439   
628    0.110877  -0.589798  -0.691958  -0.588485  -0.741596  -0.551541   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
4441  -0.386534  -0.513686  -0.297398  -0.305398  -0.501813  -0.338972   
2472   0.090358  -0.022249  -0.133709   0.160304  -0.707824  -0.297000   
3317  -0.197447  -0.137466  -0.171123  -0.313275   0.280723   0.240141   
81     0.028497  -0.151097  -0.266589  -0.227564  -0.678842  -0.851404   
4806   0.788127   1.070869   0.858960   0.621370   0.751145   0.806144   
...         ...        ...        ...        ...        ...        ...   
1392  -0.930442  -0.859001  -0.456612  -0.354545   1.611140   1.384839   
4351  -0.477864  -0.423831  -0.204767  -0.158221  -0.799932  -0.478343   
221   -0.754395  -0.780513  -0.724545  -0.611675   0.745156   0.596708   
1746  -0.017505  -0.108719  -0.117765  -0.229303  -0.046243   0.083439   
628   -0.452193  -0.386870  -0.213942  -0.216990   1.041738   0.636604   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
4441  -0.335722  -0.325250  -0.320408  -0.206188  -0.137147   0.096302   
2472  -0.316430  -0.085894   0.041440   0.193335   0.184989   0.227364   
3317   0.114708  -0.010752  -0.144363  -0.191949  -0.232896  -0.303449   
81    -0.932268  -0.877397  -0.899179  -0.640107  -0.592906  -0.354378   
4806   0.818703   0.822006   0.900412   0.705086   0.762424   0.579513   
...         ...        ...        ...        ...        ...        ...   
1392   1.108165   0.955735   0.780967   1.049272   0.924423   0.849695   
4351  -0.450440  -0.334236  -0.258129  -0.277853  -0.169850  -0.068237   
221    0.572264   0.267383   0.208195   0.290018   0.202063   0.257679   
1746   0.076778   0.246800   0.086198   0.138402  -0.083994  -0.018845   
628    0.191314  -0.142335  -0.017053  -0.138154  -0.108589  -0.164300   

      surge2_t8  surge2_t9  
4441   0.143223   0.237061  
2472   0.161235  -0.048561  
3317  -0.163204  -0.231737  
81    -0.161380  -0.206971  
4806   0.619767   0.692577  
...         ...        ...  
1392   0.885091   0.519358  
4351   0.004580   0.117441  
221    0.179069   0.305292  
1746  -0.116496  -0.152176  
628    0.142376   0.021967  

[1680 rows x 20 columns]

#### Saving models

In [40]:
dict_models = {
    'KernelRidge': regr_ridge,
    'XGBoost': regr_XGBoost,
    'SVR': regr_SVR,
    'RFR': regr_RFR
}
#    'BallTree': tree, # no predict method

In [41]:
path_model = './model/'
for name, model in dict_models.items():
    filename = path_model + name + '.sav'
    # save the model to disk
    pickle.dump(model, open(filename, 'wb'))

# Part III : Submission prediction

#### Predicting Y_test for each model using models trained using split X_train

In [42]:
# load the model from disk
all_models = [f for f in listdir(path_model) if isfile(join(path_model, f))]

for model_name in all_models:
    filename = './model/' + model_name
    loaded_model = pickle.load(open(filename, 'rb'))

    Y_test_pred = loaded_model.predict(slp_test)

    save_y_pred(model_name, output_path + "/submit/", Y_test_pred, X_test['id_sequence'], submit=True)

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
5600        0.0        0.0        0.0        0.0        0.0        0.0   
5601        0.0        0.0        0.0        0.0        0.0        0.0   
5602        0.0        0.0        0.0        0.0        0.0        0.0   
5603        0.0        0.0        0.0        0.0        0.0        0.0   
5604        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
6104        0.0        0.0        0.0        0.0        0.0        0.0   
6105        0.0        0.0        0.0        0.0        0.0        0.0   
6106        0.0        0.0        0.0        0.0        0.0        0.0   
6107        0.0        0.0        0.0        0.0        0.0        0.0   
6108        0.0        0.0        0.0        0.0        0.0        0.0   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
5600        0.0        0.0        0.0        0.0        0.0        0.0   
5601        0.0        0.0        0.0        0.0        0.0        0.0   
5602        0.0        0.0        0.0        0.0        0.0        0.0   
5603        0.0        0.0        0.0        0.0        0.0        0.0   
5604        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
6104        0.0        0.0        0.0        0.0        0.0        0.0   
6105        0.0        0.0        0.0        0.0        0.0        0.0   
6106        0.0        0.0        0.0        0.0        0.0        0.0   
6107        0.0        0.0        0.0        0.0        0.0        0.0   
6108        0.0        0.0        0.0        0.0        0.0        0.0   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
5600        0.0        0.0        0.0        0.0        0.0        0.0   
5601        0.0        0.0        0.0        0.0        0.0        0.0   
5602        0.0        0.0        0.0        0.0        0.0        0.0   
5603        0.0        0.0        0.0        0.0        0.0        0.0   
5604        0.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
6104        0.0        0.0        0.0        0.0        0.0        0.0   
6105        0.0        0.0        0.0        0.0        0.0        0.0   
6106        0.0        0.0        0.0        0.0        0.0        0.0   
6107        0.0        0.0        0.0        0.0        0.0        0.0   
6108        0.0        0.0        0.0        0.0        0.0        0.0   

      surge2_t8  surge2_t9  
5600        0.0        0.0  
5601        0.0        0.0  
5602        0.0        0.0  
5603        0.0        0.0  
5604        0.0        0.0  
...         ...        ...  
6104        0.0        0.0  
6105        0.0        0.0  
6106        0.0        0.0  
6107        0.0        0.0  
6108        0.0        0.0  

[509 rows x 20 columns]

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
5600  -0.605464  -0.351543  -1.128168  -0.759401  -0.380316  -0.775113   
5601  -0.063567  -0.139881   0.060915   0.025186   0.042977   0.409761   
5602  -0.629066  -0.667193  -0.287621   0.032828  -0.135341  -0.066547   
5603  -0.004705  -0.184260   0.050467   0.300543   0.152876  -0.031064   
5604  -0.231194   0.275523   0.122968  -0.056975   0.472361   0.632787   
...         ...        ...        ...        ...        ...        ...   
6104  -0.646428  -0.808937  -1.060435  -0.944934  -0.560933  -0.663096   
6105  -0.301380   0.068825   0.265179   0.525372   0.119438   0.221580   
6106  -0.142612  -0.509190  -0.237940  -0.353024  -0.140853   0.229921   
6107   0.080642   0.457028   0.425458  -0.050720   0.750792  -0.839876   
6108  -0.334881   0.749593   1.951795   1.490407   3.002601   1.064544   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
5600  -0.930347  -0.971967  -0.997146  -0.564322  -0.300176  -0.118046   
5601  -0.122775  -0.086519   0.708204   0.686313  -0.019024   0.021283   
5602  -0.231525  -0.390095  -0.123147  -0.455520   0.090600   0.476812   
5603  -0.076724  -0.231616  -0.151012   0.528224   0.210657   0.880883   
5604  -0.037728  -0.363414   0.155538   0.489215   0.564906   0.001292   
...         ...        ...        ...        ...        ...        ...   
6104  -0.587086  -0.286144  -0.409666  -0.244688   0.069139  -0.609462   
6105   0.187955   0.402369   0.217725  -0.022953   0.460683   0.376788   
6106  -0.244428  -0.580071  -0.334371  -0.152009  -0.523621  -0.652117   
6107   0.252422   0.706774   0.235498  -0.142840   0.392574   0.105053   
6108   0.908496   0.823064   0.354190  -0.541486  -0.421022   0.024369   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
5600  -0.246792  -0.249534   0.129161  -0.033038  -0.523397   0.346199   
5601  -0.077324   0.747948   0.642704   0.348651  -0.115248   0.846381   
5602   0.291283   0.004482   0.653666   0.918983   0.133319   0.041931   
5603   0.650131   0.699566   0.450404   0.641901   0.205088   0.572806   
5604   0.861486   0.192273   0.941854   0.815560  -0.429089   0.709424   
...         ...        ...        ...        ...        ...        ...   
6104  -0.659200  -0.991651  -0.911690  -0.702406  -0.100041   0.004690   
6105   0.409784   0.774568   0.991786   0.591912   0.843347   0.295935   
6106  -0.315269  -0.086796  -0.127246  -0.379799  -0.067569  -0.175752   
6107  -0.590026   0.064705  -0.103954  -0.452475  -0.292673  -0.248487   
6108  -0.433752  -0.973147  -0.947557  -0.101721   0.170076   0.227756   

      surge2_t8  surge2_t9  
5600   0.148681   0.233831  
5601   0.457371  -0.292193  
5602  -0.064879  -0.335583  
5603  -0.142747   0.483519  
5604   0.697304   0.063574  
...         ...        ...  
6104  -0.574959  -0.763780  
6105   0.381149  -0.013975  
6106   0.035016  -0.063235  
6107   0.322369   0.367232  
6108  -0.374153   0.076130  

[509 rows x 20 columns]

#### Predicting Y_test for the best model using all of X_train to train : no gain for XGBoost

In [49]:
slp_train

array([[100849.72, 100797.72, 100754.72, ..., 101970.81, 101981.81,
        101990.81],
       [100940.37, 100881.37, 100823.37, ..., 101515.72, 101562.72,
        101611.72],
       [101862.91, 101879.91, 101894.91, ..., 101005.37, 101038.37,
        101076.37],
       ...,
       [102048.13, 102080.13, 102106.13, ..., 100781.81, 100724.81,
        100664.81],
       [102111.95, 102134.95, 102149.95, ..., 101352.13, 101376.13,
        101392.13],
       [101972.53, 101984.53, 101993.53, ..., 100412.28, 100450.28,
        100483.28]], dtype=float32)

In [50]:
surge_train_df

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
1      0.586936   1.069580   0.767928  -0.100162   0.070775  -0.244285   
2      0.767928  -0.100162   0.070775  -0.244285  -0.354891  -0.928031   
3      0.070775  -0.244285  -0.354891  -0.928031  -0.773853  -0.375001   
4     -0.354891  -0.928031  -0.773853  -0.375001  -0.361594  -0.210768   
5     -0.773853  -0.375001  -0.361594  -0.210768   0.288635  -0.726929   
...         ...        ...        ...        ...        ...        ...   
5595   1.451674   1.220407   0.556771   1.709754   0.483033   0.533309   
5596   0.556771   1.709754   0.483033   0.533309   1.448322   1.820360   
5597   0.483033   0.533309   1.448322   1.820360   1.662831   1.528763   
5598   1.448322   1.820360   1.662831   1.528763   1.284089   0.070775   
5599   1.662831   1.528763   1.284089   0.070775   0.888589   1.545521   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
1     -0.354891  -0.928031  -0.773853  -0.375001  -0.053886   0.356847   
2     -0.773853  -0.375001  -0.361594  -0.210768   0.348464   0.264641   
3     -0.361594  -0.210768   0.288635  -0.726929   0.901696   0.449052   
4      0.288635  -0.726929  -0.576103   1.160076   0.113760  -0.422707   
5     -0.576103   1.160076   0.442813   0.305393  -0.456236  -0.825057   
...         ...        ...        ...        ...        ...        ...   
5595   1.448322   1.820360   1.662831   1.528763   0.759197   0.884931   
5596   1.662831   1.528763   1.284089   0.070775   0.298171  -0.397560   
5597   1.284089   0.070775   0.888589   1.545521  -0.540059  -0.498148   
5598   0.888589   1.545521   1.166779   0.653970  -0.498148  -0.405942   
5599   1.166779   0.653970   0.409296   0.137809   0.164054   0.331700   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
1      0.348464   0.264641   0.901696   0.449052   0.113760  -0.422707   
2      0.901696   0.449052   0.113760  -0.422707  -0.456236  -0.825057   
3      0.113760  -0.422707  -0.456236  -0.825057  -0.992703  -0.992703   
4     -0.456236  -0.825057  -0.992703  -0.992703  -0.322119  -0.883733   
5     -0.992703  -0.992703  -0.322119  -0.883733  -0.473001  -0.422707   
...         ...        ...        ...        ...        ...        ...   
5595   0.298171  -0.397560  -0.540059  -0.498148  -0.498148  -0.405942   
5596  -0.540059  -0.498148  -0.498148  -0.405942   0.164054   0.331700   
5597  -0.498148  -0.405942   0.164054   0.331700   1.052577   1.220223   
5598   0.164054   0.331700   1.052577   1.220223   1.446545   2.670360   
5599   1.052577   1.220223   1.446545   2.670360   2.620066   2.678742   

      surge2_t8  surge2_t9  
1     -0.456236  -0.825057  
2     -0.992703  -0.992703  
3     -0.322119  -0.883733  
4     -0.473001  -0.422707  
5     -0.473001  -0.531677  
...         ...        ...  
5595   0.164054   0.331700  
5596   1.052577   1.220223  
5597   1.446545   2.670360  
5598   2.620066   2.678742  
5599   1.220223   0.725668  

[5599 rows x 20 columns]

###  End of notebook

In [43]:
# End of pipeline time
t1 = time()
print("computing time : {:8.6f} sec".format(t1 - t0))
print("computing time : " + strftime('%H:%M:%S', gmtime(t1 - t0)))

computing time : 1575.047060 sec
computing time : 00:26:15
